services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-vector-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb_network
    restart: always

networks:
  mongodb_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
